{% set name = "xmlstore" %}
{% set version = "0.9.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xmlstore-{{ version }}.tar.gz
  sha256: 53c73c1e36fa55f2f68a0e6931678b90d652be958676d48c35811093eee00567

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8

test:
  imports:
    - xmlstore
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BoldingBruggeman/xmlstore
  summary: 'Python package for storing typed data in xml'
  description: |
    xmlstore is a Python package for storing information in XML format
    with extensible support for typing and schema validaton
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
