{% set name = "xmlstore" %}
{% set version = "0.9.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmlstore-{{ version }}.tar.gz
  sha256: 2b534103f0161a5ef7e5958beffadb262922524eb25bd07846593e8b89c6a3d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - xmlstore
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/BoldingBruggeman/xmlstore
  summary: 'Python package for storing typed data in xml'
  description: |
    xmlstore is a Python package for storing information in XML format
    with extensible support for typing and schema validaton
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
