{% set name = "xmlstore" %}
{% set version = "0.9.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BoldingBruggeman/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2815ba7c5d845bb3de065cd418cd274f88ed441200ff665bd82c977776bf46c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8

test:
  imports:
    - xmlstore
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BoldingBruggeman/xmlstore
  summary: 'Python package for storing typed data in xml'
  description: |
    xmlstore is a Python package for storing information in XML format
    with extensible support for typing and schema validaton
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
