{% set name = "xmlstore" %}
{% set version = "0.9.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmlstore-{{ version }}.tar.gz
  sha256: aa758717e330cc6b7d72e41d1125d062531da3ff724551c3683b9d0b13425fb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - xmlstore
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/BoldingBruggeman/xmlstore
  summary: 'Python package for storing typed data in xml'
  description: |
    xmlstore is a Python package for storing information in XML format
    with extensible support for typing and schema validaton
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
